### ISSUE TITLE
Help with the code

### ISSUE THREAD

**Issue by Rushuby** [ManavvGarg/Discord-Moderation-Bot#37]
`Debugger attached.
Waiting for the debugger to disconnect...
c:\Users\diara\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The module '\\?\c:\Users\diara\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 88. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1150:18)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at bindings (c:\Users\diara\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (c:\Users\diara\node_modules\better-sqlite3\lib\database.js:9:24)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32) {
  code: 'ERR_DLOPEN_FAILED'
}
`

i have no idea how to fix it

**Comment by ManavvGarg** [comment]
Just install all the node modules manually instead of doing npm i

This usually fixes this issue.
