### ISSUE TITLE
the prefix command leaves this issue 

### ISSUE THREAD

**Issue by ghost** [ManavvGarg/Discord-Moderation-Bot#38]
(node:397) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.run (/home/runner/Proton/commands/main/prefix.js:30:23)
    at Client.<anonymous> (/home/runner/Proton/index.js:82:17)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/home/runner/Proton/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/Proton/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/Proton/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/Proton/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/Proton/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/Proton/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/runner/Proton/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:315:20

**Comment by ManavvGarg** [comment]
Something is not defined, probably because you changed something. It works fine at my end.
