### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by coco66688** [ManavvGarg/Discord-Moderation-Bot#45]
(node:31300) UnhandledPromiseRejectionWarning: TypeError: Spotify option "clientID" must be present and be a non-empty string.
    at check (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\erela.js-spotify\dist\plugin.js:37:15)
    at new Spotify (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\erela.js-spotify\dist\plugin.js:53:9)
    at module.exports (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\events\client\ready.js:29:16)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ManavvGarg** [comment]
Thanks for notifying! The bug has been fixed. Please use the latest "ready.js" event file to fix your issue.

**Comment by coco66688** [comment]
TypeError: Cannot read property 'id' of null
    at Client.<anonymous> (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\index.js:38:66)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\ws\lib\websocket.js:797:20)
