### ISSUE TITLE
bug (2)

### ISSUE THREAD

**Issue by coco66688** [ManavvGarg/Discord-Moderation-Bot#46]
TypeError: Cannot read property 'id' of null
    at Client.<anonymous> (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\index.js:38:66)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\user\Downloads\Discord-Moderation-Bot-main\Discord-Moderation-Bot-main\node_modules\ws\lib\websocket.js:797:20)

**Comment by ManavvGarg** [comment]
Fixed. Check latest commit
